### ISSUE TITLE
Megacmd missing dev-libs/libsodium dependency

### ISSUE THREAD

**Issue by Gosha** [4nykey/4nykey#13]
`"dev-libs/libsodium"` @ https://github.com/4nykey/4nykey/blob/9713d732936ea0786f32d0313778e7fcc499d84a/net-misc/megacmd/megacmd-9999.ebuild#L30..L34

**Comment by Gosha** [comment]
Oh, and `USE=sodium` on `net-misc/meganz-sdk`

**Comment by 4nykey** [comment]
Ok, sdk includes sodium headers unconditionally, so libsodium's a required dep now, apparently. I changed the involved ebuilds in 550978f. If something's still wrong I'll need to have a look at build logs and/or emerge -p output.

**Comment by Gosha** [comment]
Looks like it's working just fine now. Thanks
