### ISSUE TITLE
megasync-3.6.0.0

### ISSUE THREAD

**Issue by kajzersoze** [4nykey/4nykey#14]
!!! No known mirror by the name: githubcl
>>> Downloading 'http://distfiles.gentoo.org/distfiles/megasync-3.6.0.0.tar.gz'
--2018-01-31 21:36:28--  http://distfiles.gentoo.org/distfiles/megasync-3.6.0.0.tar.gz
Resolving distfiles.gentoo.org... 64.50.236.52, 137.226.34.46, 156.56.247.195, ...
Connecting to distfiles.gentoo.org|64.50.236.52|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-01-31 21:36:29 ERROR 404: Not Found.

!!! Couldn't download 'megasync-3.6.0.0.tar.gz'. Aborting.

**Comment by 4nykey** [comment]
It's certainly there, see https://github.com/4nykey/4nykey/blob/master/profiles/thirdpartymirrors. You can edit the ebuild, if you don't need the repo in whole.

**Comment by kajzersoze** [comment]
I see, thing is I'm not using the overlay, just downloaded ebuild and files dir.
That's why it wasn't working.
Yeah, I fixed it manually.

**Comment by sedimentation-fault** [comment]
I had the same problem and copying 

https://github.com/4nykey/4nykey/blob/master/profiles/thirdpartymirrors

to the profiles directory of my local overlay solved it (I just copied the three packages net-misc/megasync/, net-misc/meganz-sdk/, dev-libs/breakpad/ to my local overlay, I didn't mirror the whole repository through layman).

I can report that megasync 4.3.7.0 from your repo compiles and works fine this way. Thank you very much! :-)
