### ISSUE TITLE
media-libs/qm-dsp-1.7.1_p20170314 - build failure due to "-Werror"

### ISSUE THREAD

**Issue by stefantalpalaru** [4nykey/4nykey#16]
With gcc-7.3.0-r1:

x86_64-pc-linux-gnu-g++ -O3 -march=native -pipe -O3 -march=native -pipe -DNDEBUG -Wall -Wextra -Werror=implicit-function-declaration  -fPIC -ffast-math -msse -msse2 -mfpmath=sse -ftree-vectorize -DUSE_PTHREADS -I. -DNO_BLAS_WRAP -DADD_  -Iext/kissfft -Iext/kissfft/tools -Dkiss_fft_scalar=double -Werror -I. -Iext/kissfft -Iext/kissfft/tools -Dkiss_fft_scalar=double   -c -o dsp/tempotracking/TempoTrack.o dsp/tempotracking/TempoTrack.cpp

[...]

In member function ‘int TempoTrack::findMeter(double*, int, double)’:
cc1plus: error: assuming signed overflow does not occur when assuming that (X + c) >= X is always true [-Werror=strict-overflow]
cc1plus: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]

**Comment by 4nykey** [comment]
Couldn't reproduce, anyway we're now dropping any extra cflags.
