### ISSUE TITLE
media-gfx/natron-2.3.11 - compilation error with the "pch" USE flag

### ISSUE THREAD

**Issue by stefantalpalaru** [4nykey/4nykey#20]
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: pch/HostSupport: No such file or directory

**Comment by 4nykey** [comment]
Build logs?
- output of `emerge --info media-gfx/natron`
- contents of `/var/tmp/portage/media-gfx/natron-2.3.11/temp/build.log`

**Comment by stefantalpalaru** [comment]
`emerge --info`: https://paste.pound-python.org/show/NFMW37qxcYWGr1YIVoD9/

Build log for `USE="pch" emerge natron`: https://paste.pound-python.org/show/bko01iB81RTSHQXlQidA/

**Comment by 4nykey** [comment]
Tried with your FLAGS and MAKEOPTS, natron still builds.

I see you've got gcc8 installed, is gcc7 set as current compiler?
`gcc-config -c`

Try to lower your MAKEOPTS. Start with
`MAKEOPTS='-j1' ebuild <...>/media-gfx/natron/natron-2.3.11.ebuild clean compile`

USE=-pch if it still fails

**Comment by stefantalpalaru** [comment]
You can see on the first line of the `emerge --info` output that the active compiler is gcc-7.3.0.
Are you running ~amd64 like I am, or some combination of stable and unstable packages?

**Comment by 4nykey** [comment]
Yes, ~amd64. And yet I couldn't reproduce this. This looks like make or, less likely, qmake issue.
Try with MAKEOPTS='-j1'.

**Comment by 4nykey** [comment]
Ah so. From my limited understanding, gcc7.3 -march=native ain't so reliable for your particular hardware.
The only thing I could offer is to automatically append -Winvalid-pch to flags, so the error is more apparent.

**Comment by stefantalpalaru** [comment]
It's a GCC bug that seems to have been fixed in trunk: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86007

My workaround, until I can upgrade to gcc-8.2.0, is to add "-mlwp" after "-march=native" in my CFLAGS. I can compile Natron with the "pgo" USE flags with that.
