### ISSUE TITLE
www-client/torbrowser: add use flag to {en,dis}able google location

### ISSUE THREAD

**Issue by Ud71p** [4nykey/4nykey#24]
This part of the ebuild failed my audit:

	# Setup api key for location services
	echo -n "${_google_api_key}" > "${S}"/google-api-key
	mozconfig_annotate '' --with-google-api-keyfile="${S}/google-api-key"

The audience for torbrowser is mostly people really caring about privacy, so it would be nice to be able to disable this part with a use flag.

**Comment by 4nykey** [comment]
Apparently it doesn't make sense for torbrowser at all. So I removed google api key parts altogether.

**Comment by Ud71p** [comment]
Even better, thanks.
