### ISSUE TITLE
www-client/torbrowser: UI is broken

### ISSUE THREAD

**Issue by PF4Public** [4nykey/4nykey#43]
I've tried to build www-client/torbrowser with the following USE flags:
```
www-client/torbrowser-68.2.0.9.0.0.1.1::4nykey was built with the following:
USE="dbus eme-free hardened hwaccel lto pulseaudio screenshot startup-notification system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-sqlite system-webp wifi -bindist -clang -custom-cflags -custom-optimization -debug -geckodriver -gmp-autoupdate -jack (-neon) -pgo (-selinux) -test -wayland" ABI_X86="(64)" CPU_FLAGS_X86="avx2"
```
It did compile successfully, but the UI is broken for some reason.
See the image:
![Screenshot](https://user-images.githubusercontent.com/10319700/68245341-d37b0200-0027-11ea-9381-21d96510d381.png)

It also logs following errors:
```
JavaScript error: chrome://torbutton/content/tor-circuit-display.js, line 442: TypeError: myController is null
JavaScript error: chrome://torbutton/content/tor-circuit-display.js, line 442: TypeError: myController is null
JavaScript error: resource:///modules/sessionstore/SessionStore.jsm, line 1325: uncaught exception: 2147746065
JavaScript error: resource://gre/modules/ExtensionContent.jsm, line 554: TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.
JavaScript error: resource:///modules/TorProtocolService.jsm, line 6: TypeError: Cc['@torproject.org/torlauncher-protocol-service;1'] is undefined
JavaScript error: chrome://browser/content/preferences/in-content/preferences.js, line 96: ReferenceError: can't access lexical declaration `gTorPane' before initialization

```
Building with:
```
www-client/torbrowser-68.2.0.9.0.0.1.1::4nykey was built with the following:
USE="dbus gmp-autoupdate pulseaudio screenshot startup-notification system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-sqlite system-webp wifi -bindist -clang -custom-cflags -custom-optimization -debug -eme-free -geckodriver -hardened -hwaccel -jack -lto (-neon) -pgo (-selinux) -test -wayland" ABI_X86="(64)" CPU_FLAGS_X86="avx2"
```
didn't help either.

What is wrong here?

**Comment by 4nykey** [comment]
Yes, broken indeed.

See `Torbutton And Tor Launcher Integration` section for [Tor Browser 9.0](https://blog.torproject.org/new-release-tor-browser-90): 
> We redesigned the bridge and proxy configuration dialogs and include them directly into the browser's preference settings

Since we're runnig a system instance of tor daemon, I think it's safe to disable Tor settings in preferences. Try -r1 (0b101d7)

**Comment by PF4Public** [comment]
> Since we're runnig a system instance of tor daemon, I think it's safe to disable Tor settings in preferences. Try -r1 ([0b101d7](https://github.com/4nykey/4nykey/commit/0b101d72f3c9c3de608cf6930eb1f97beff25205))

Preferences now open, but network configuration is completely absent and probably because of that network connectivity is broken. Even though `about:config` has all the settings correct, it doesn't even try to establish any connection with tor.

**Comment by 4nykey** [comment]
Is tor running? See https://wiki.gentoo.org/wiki/Tor#Configuration
Another thing: the tor and torbrowser default setting for SocksPort are different (9050 and 9150 resp.)
so either
- add a line saying `SocksPort 9150` to /etc/tor/torrc or
- set `network.proxy.socks_port` to 9050 in torbrowser's `about:config`

then restart both

**Comment by PF4Public** [comment]
> Another thing: the tor and torbrowser default setting for SocksPort are different (9050 and 9150 resp.)

Ah, I feel stupid now. I have verified that tor is working via another browser, I have checked torbrowser settings multiple times, but didn't notice that nasty **1** in port number.

Thanks.
