### ISSUE TITLE
Can't get gpaste extension working

### ISSUE THREAD

**Issue by teresaejunior** [4nykey/4nykey#55]
I have installed gpaste 3.34.1 on the latest stable GNOME with systemd, but I was unable to add the extension to the panel.

First, there was an error about not being able to find the "Settings schema", which I fixed by running `sudo glib-compile-schemas /usr/share/glib-2.0/schemas`.

But now, I'm getting:

```
gnome-shell[2041]: Received error from DBus search provider org.gnome.GPaste.Ui.desktop: Gio.IOErrorEnum: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit dbus-org.gnome.GPaste.service not found.
dbus-daemon[1973]: [session uid=1000 pid=1973] Activating via systemd: service name='org.gnome.GPaste.Ui' unit='org.gnome.GPaste.Ui.service' requested by ':1.22' (uid=1000 pid=2041 comm="/usr/bin/gnome-shell ")
dbus-daemon[1973]: [session uid=1000 pid=1973] Activation via systemd failed for unit 'org.gnome.GPaste.Ui.service': Unit org.gnome.GPaste.Ui.service not found.
```

Any ideas? Thanks!

**Comment by 4nykey** [comment]
Glib schemas compile are back (were lost at some point). As for dbus / systemd no idea, try to logout / login back perhaps.

**Comment by teresaejunior** [comment]
Thanks for your answer! Today I upgraded to GNOME 3.36, and I'm unable to test now, because I don't really understand yet how slots work: gpaste requires `>=x11-wm/mutter-3.36:0/6[introspection]`, but I have `3.36.2(0/4)[introspection]`.
