### ISSUE TITLE
net-misc/megasync-4.3.9: Any plan to update to 4.4.x ?

### ISSUE THREAD

**Issue by HougeLangley** [4nykey/4nykey#70]
I realized the new stable version is 4.4.x, any plan to update ?

**Comment by 4nykey** [comment]
Yes, eventually.
The whole idea was to have a separate mega sdk package to be used by both megasync and megacmd.
Newer megasync versions require more recent sdk. megacmd in turn has to be updated to newer sdk but usually it lags behind megasync badly

**Comment by HougeLangley** [comment]
OK, Thanks buddy.
