### ISSUE TITLE
=net-misc/megasync-3.0.1 build failure

### ISSUE THREAD

**Issue by hnaparst** [4nykey/4nykey#8]
In file included from mega/include/mega/types.h:60:0,
                 from mega/include/mega/utils.h:25,
                 from mega/include/mega/attrmap.h:25,
                 from mega/src/attrmap.cpp:22:
mega/include/mega/crypto/sodium.h:27:20: fatal error: sodium.h: No such file or directory
compilation terminated.
make[1]: *** [Makefile:1716: attrmap.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from mega/include/mega/types.h:60:0,
                 from mega/include/mega/waiter.h:25,
                 from mega/src/backofftimer.cpp:22:
mega/include/mega/crypto/sodium.h:27:20: fatal error: sodium.h: No such file or directory
compilation terminated.

**Comment by hnaparst** [comment]
git commit 06d9ffecbc543318489dea36577a0184aa802baf works fine, though.

**Comment by 4nykey** [comment]
Sodium mentioned as an optional dep, apparently it ain't completely optional. I've added depend on libsodium (7430d96), check if it helps.

**Comment by hnaparst** [comment]
=net-misc/megasync-3.0.1-r1 emerges and runs correctly now. Thanks.

**Comment by 4nykey** [comment]
Actualy there was a braindamaged error in the ebuild causing it to fetch older sources, corrected and renamed to v3.0.1.0 so distfiles won't clash (0015474)

**Comment by hnaparst** [comment]
3.0.1-r1 was probably the correct name to use if the error was in the ebuild.  Thanks for your work on megasync.   I was mostly interested in MEGA because of their 50GB free limit.  However, since they do not save previous versions like Dropbox and S3 do, I am thinking about using S3 instead for my 7 GB....
