### ISSUE TITLE
ebuild for skia-113 branch to debug build failures on arm/arm64

### ISSUE THREAD

**Issue by stefson** [4nykey/4nykey#82]
hey there, 

do you think you're able to add a live ebuild for the skia m113 branch? It will help me greatly to debug compile issues with firefox nightly, to which the m113 has been added, on arm/arm64. 

thanks a lot

**Comment by 4nykey** [comment]
Hello, I'll be AFK for about a week.
Yes, I could add an ebuild for the branch, it's just I won't be able to
test it for the ARM arch, no compatible hw in the reach, I'm afraid.

**Comment by stefson** [comment]
yes thats no problem, I need this for testing skia on arm hardware and hopefully finding a few arm specific bugs in the process. 

It seems you have to incoperate a certain wuffs snapshot (https://skia.googlesource.com/external/github.com/google/wuffs-mirror-release-c.git) into the live ebuild, which is the point where I failed to fix it.

**Comment by 4nykey** [comment]
> yes thats no problem, I need this for testing skia on arm hardware and hopefully finding a few arm specific bugs in the process.
>
> It seems you have to incoperate a certain wuffs snapshot (https://skia.googlesource.com/external/github.com/google/wuffs-mirror-release-c.git) into the live ebuild, which is the point where I failed to fix it.

In the meantime I plain disabled wuffs in the ebuild:
https://github.com/4nykey/4nykey/commit/8ae706c

If wuffs support is crucial, let me know

**Comment by stefson** [comment]
thanks for the ebuild, it was helpfull with debugging arm things :)
